
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ikmassessment
    username: postgres
    password: 123
  liquibase:
    # enabled: 'true'
    drop-first: 'false'
    change-log: classpath:/db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none

